### ISSUE TITLE
Crear escala alternativa de valores en el eje derecho del gráfico

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-explorer#112]
**Contexto**

La implementación actual del gráfico no admite la consulta de series con distintas escalas en una misma consulta.

Una serie que es un índice no se puede visualizar bien con una serie que es un %.

**Propuesta**

Implementar una asignación automática de series "fuera de escala" al eje alternativo derecho.

La idea es que la primer serie (o "las series que ya están") definen la escala del eje principal (izquierdo) y las series que se agregan van ahí por default salvo que estén "fuera de escala", en cuyo caso van al eje alternativo (derecho).

Fuera de escala:

1. El valor mínimo de la serie a agregar está por encima del valor máximo del eje principal (izq).
2. El valor máximo de la serie a agregar está por debajo del valor mínimo del eje principal (izq).
3. El promedio de los valores de la serie a agregar está un orden de magnitud por encima o por debajo del promedio de los valores de las series que ya están en el eje principal (o de los valores del eje principal).

Se define a una serie como "fuera de escala" siempre que cumpla con la condición 3 + la condición 1 o la condición 2. Esto está pensado así para hacer la re-asignación _únicamente_ si la serie realmente _no se podría visualizar razonablemente_ en caso de asignarla al mismo eje. Se preserva el eje principal a toda costa.

**Notas**

+ Las condiciones se pueden implementar tanto sobre el cálculo min, max, avg de los valores de las series, como de los valores del eje (lo que sea más performante o más preciso).

+ Tal vez los valores min, max y avg de las series pueden ser precalculados por default al momento de la consulta para que sea más performante la experiencia (incluso podríamos pensar si esto debería venir directamente de la API, como parte de los metadatos enriquecidos que calcula de cada serie al momento de indexación).

**Comment by abenassi** [comment]
@alejandrosobko, acá veo que más o menos todo lo que hablamos ayer estaba bajado en el issue, pero te agrego indicación de cómo tratar el label de los ejes verticales en distintos escenarios:

+ Si hay una sola serie en el eje, el label es el "units" de esa serie (esto da más información que "Valores").
+ Si hay más de una serie pero los "units" son textualmente idénticos entre _todas las series de ese eje_, el label sigue siendo "units" (puesto una sola vez).
+ Si hay más de una serie pero los "units" _uniques_ son más de uno (hay diferencias entre ellos), pondría el label agregando todos ellos de una forma "compacta" (con una separación de salto de línea `/n` o separados por comas, lo que quede mejor). Este último caso estaría bueno verlo en vivo para ver opciones de cómo hacer que quede bien, pero lo más compacto posible para que no robe espacio al gráfico.

**Comment by alejandrosobko** [comment]
@abenassi esto aplica para ambos ejes no? Es decir, si tenemos 2 series en el eje Y izquierdo que una dice "motos" y la otra serie dice "unidades" y luego en el eje Y derecho tenemos "unidades" "dolar", vamos a ver las 4 series en el gráfico pero del lado izquierdo dice "motos, unidades" y del lado derecho dice "unidades, dolar". Es así? O esto de juntar los labels sólo aplica para el eje alternativo (derecho)?

**Comment by abenassi** [comment]
Ale, aplica para los dos ejes, tal como decís!
