### ISSUE TITLE
Agregar metadatos al footer del gráfico de cada serie

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-explorer#161]
En esta sección, agregar los siguientes metadatos:

<img width="977" alt="screenshot 2018-08-14 20 03 55" src="https://user-images.githubusercontent.com/4405346/44123603-76f99764-9fff-11e8-88e9-24cfb81436aa.png">

+ Agregar identificador de la serie entre paréntensis en la propia descripción de la serie (similar a como lo hace FRED):

<img width="557" alt="screenshot 2018-08-14 20 06 04" src="https://user-images.githubusercontent.com/4405346/44123617-837a55b4-9fff-11e8-8672-38d73c3caca2.png">

+ "Unidades:" poner debajo de "Frecuencia de actualización:" (utilizar el mismo metadato que se usa para este campo en el preview de las series en el buscador)

+ "Dataset:" poner debajo de "Unidades:" y usar el metadato "dataset_title" para poner acá (igual que en el preview).

+ "Distribución:" poner debajo de "Dataset:" y usar el metadato "distribution_title" para poner acá.

+ Agregar la cantidad de valores en el mismo lugar que "Cobertura temporal", entre paréntesis, de la siguiente forma: "Cobertura temporal: 2004 a 2017 (13 valores)". Usar el metadato "time_index_size" para esto.

**Comment by abenassi** [comment]
@alejandrosobko ayer tuvimos una demo de improviso del explorer y surgió la necesidad de agregar más metadatos a esta parte (es la que en última instancia te "asegura" de qué se trata la serie y todo lo que puedas entender para usarla). Podremos agregar ese último issue a la versión 1.0??? Es sólo agregar metadatos que la API ya devuelve. Gracias!!!

**Comment by alejandrosobko** [comment]
@abenassi Dale, cuando lo tenga lo subo.

**Comment by abenassi** [comment]
Gracias!!
