### ISSUE TITLE
Corregir las tarjetas de visualización de resultados en la búsqueda.

### ISSUE THREAD

**Issue by sebasbarraud** [datosgobar/series-tiempo-ar-explorer#168]
Básicamente falta agregar algunos metadatos en los resultados de las series. En estos mocks se ve todo lo que deberían contener en sus diferentes estados.
![series de tiempo iteracion 4_1 home](https://user-images.githubusercontent.com/33296388/44174747-70b3e880-a0ba-11e8-90d6-531d4df714ef.png)
![series de tiempo iteracion 4_2 resultados](https://user-images.githubusercontent.com/33296388/44174748-70b3e880-a0ba-11e8-8259-585f6ba63852.png)

**Comment by abenassi** [comment]
Agrego comentario:

+ El título de la serie (que es el metadato field_description) debería tener hasta 2 lineas para que se vea mejor cuando la tarjeta es muy chica.

**Comment by alejandrosobko** [comment]
@abenassi hay algunos cambios de estilos en estos ejemplos. Los aplico o mantengo lo que ya tenemos pero solo agrego la nueva info?

**Comment by abenassi** [comment]
Hola Ale, sí le estuvimos haciendo una revisión a los estilos de las
tarjetas para volverlas más efectivas. Así que van con estilo nuevo y todo.
De todas maneras tenemos que probar como quedan con el cambio y puede haber
más adelante otra iteración, cuando podamos testear esta mejora. Gracias!!

**Comment by abenassi** [comment]
Los mini-gráficos de las tarjetas muestran los últimos X períodos de la serie (no la serie completa) dependiendo de la frecuencia de la serie:

+ Diaria: últimos 90 períodos
+ Mensual: últimos 24 períodos
+ Trimestral: últimos 20 períodos
+ Semestral: últimos 10 períodos
+ Anual: últimos 10 períodos

**Comment by abenassi** [comment]
@alejandrosobko te paso algunas corecciones para hacer:

+ El título principal de la tarjeta debería tener 2 líneas (tiene solo una)
+ Deberíamos sacarle un poco de padding (tiene demasiados márgenes). Ahí te paso un screenshot que hizo @sebasbarraud corrigiendo los valores para que quede mejor

![Screen Shot 2018-11-27 at 16.29.18.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5669d6f56378e7130054f97e/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226456f46b7191a379e90c2958415e46be5d4a1f06a3a3dc78e2a436628f0e08e9876e0b70973d42ffba821fbf00e871894f81e2b59850d2aa6c7bb3d4d216744b470a83ed5c32aa984ecc5bf54fe64f50a5123065f43b.png)

**Comment by abenassi** [comment]
+ Corregir funcionamiento entre el texto y el gráfico que en mobile rompe
![Screenshot 2018-11-27 16.38.59.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5669d6f56378e7130054f97e/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cc6417763e7b53e37a26cbb070f1172243434d0eee1e020a17b8eb8339a3e43f74dc5f5fe9806d0c27c43d11acb9d04ebd01be74825d99a4fedb1294b7607caddecd5d340c041f83fe5831a39a4fcf5df049e9455cb65e.png)

**Comment by abenassi** [comment]
@alejandrosobko en el mini gráfico también hay que resolver la conversión correcta al formato % (te falta multiplicar por 100).

![Screenshot 2018-11-27 17.06.28.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5669d6f56378e7130054f97e/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cc6417763e7b53e37a27cbb37ef1102343434d0eee1e020a17b8eb8339a3e43f74dc5f5fe9806d0c27c43d11acb9d04ebd01be74825d99a4fedb1294b7607caddecd5d340c041183fe5831a39a4fc15af54ee34f54b65e.png)
