### ISSUE TITLE
Agregar "reset zoom"

### ISSUE THREAD

**Issue by alejandrosobko** [datosgobar/series-tiempo-ar-explorer#176]
Antes con Highcharts teníamos el botón "Reset zoom". Volver a agregarlo y posicionarlo al lado de los datepickers.

**Comment by abenassi** [comment]
@alejandrosokobo, se puede hacer fácilmente que cuando el zoom está al "máximo" no aparezca el botón "Reiniciar zoom" (que no sea visible) y que sólo sea visible cuando _podría ser usado con provecho_ porque el zoom no está al máximo?

**Comment by alejandrosobko** [comment]
@abenassi no se qué tan fácil será, pero se puede agregar. Podrías cargar un issue nuevo así no reutilizamos este si te parece. Yo creo que es lo mejor.

**Comment by abenassi** [comment]
Dale perfecto!
