### ISSUE TITLE
Implementar CDN para distribuir versiones estables del explorador

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-explorer#189]
+ Usar jsdeliver. 

+ El Github Pages de `series-tiempo-ar-explorer` refleja la versión de master y no usa el CDN. Esta versión está buildeada con `make build`.

+ Cuando hay una versión considerada estable, se buildea usando `make release`, commiteando y taggeando la versión.

+ Agregar este procedimiento al README del proyecto.

+ El build tiene que incluir los js y los css necesarios para distribuir el explorador.

**Comment by alejandrosobko** [comment]
Esta tarea fue estimada teniendo en cuenta que hay que realizar lo siguiente:
- actualizar el README
- modificar el proceso de _bundle_ que hoy tenemos para que Webpack incluya todo el CSS de la aplicación dentro de uno solo, el cual será usado para entregar como distribuíble.
