### ISSUE TITLE
Agregar un "Cargando..." en la home del explorador y en otras pantallas que cargan resultados

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-explorer#195]
Consultado desde datos.gob.ar/series a veces tarda un poco y habría que aclarar al usuario que algo está pasando y requiere algo de tiempo.

**Comment by abenassi** [comment]
@alejandrosokobo, me parece que faltaba agregarlo en la carga inicial de la home de la aplicación esto no?? Que en lugar de ponerse en blanco mientras carga las tarjetas destacadas, aparezca un loading hasta que pueda cargar todo.

**Comment by alejandrosobko** [comment]
Sí @abenassi, cargué un issue nuevo acá https://waffle.io/datosgobar/series-tiempo-ar-explorer/cards/5bb3c86e67cb1c00399bee53

**Comment by abenassi** [comment]
Perfecto!
