### ISSUE TITLE
Exportar como imagen: recortar el render de la imagen a descargar para que sólo muestre el gráfico y no los componentes

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-explorer#216]
La imagen a exportar del gráfico no debería tener componentes web que sólo tienen sentido cuando se puede interactuar con ellos.
![chart 10](https://user-images.githubusercontent.com/4405346/46492596-65408c00-c7e4-11e8-8893-72a88541649b.png)

**Comment by alejandrosobko** [comment]
@abenassi querés que suceda lo mismo al momento de imprimir? ("imprimir gráfico")

**Comment by abenassi** [comment]
Sí, si se puede también!

**Comment by abenassi** [comment]
+ Ocultar el navigator (se ve en print)
+ Agregar las leyendas con el default de highcharts

**Comment by alejandrosobko** [comment]
Esta tarea no incluye mostrar la leyenda, para eso está https://waffle.io/datosgobar/series-tiempo-ar-explorer/cards/5bb651e7eae9e200392a301c
