### ISSUE TITLE
Exportar como imagen: agregar leyenda de las series que se ven en el gráfico

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-explorer#217]
Si se puede, agregar abajo del gráfico en lugar de arriba (sólo para exportar la imagen! no en el gráfico web).
<img width="332" alt="screenshot 2018-10-04 14 47 00" src="https://user-images.githubusercontent.com/4405346/46492614-76899880-c7e4-11e8-880e-a9f3cd6e9f71.png">

**Comment by alejandrosobko** [comment]
No tenemos forma de hacer esto usando highcharts. Encuentro 2 opciones:
* `window.print()` esto imprime toda la pantalla, y podemos jugar con CSS para ocultar todo menos el gráfico y los tags, pero sirve SOLO para imprimir.
* No usamos la funcionalidad de highcharts de exportar y agregamos una librería nueva que nos permita definir qué elementos queremos generar para exportar. Esta última opción no la conozco pero seguro tenemos forma.

**Comment by alejandrosobko** [comment]
Agregar la leyenda de highcharts y ocultarla con CSS. Mostrarla en @print.

**Comment by abenassi** [comment]
@alejandrosobko esto debería volver a To Do, no?? No está implementado todavía?
