### ISSUE TITLE
Agregar código para embeber el gráfico en una página web

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-explorer#220]
Como nueva opción para "Compartir" además de la URL, CSV y JSON: agregar el código (se copia al portapapeles igual que las otras opciones) para embeber el componente del gráfico en un sitio web.

Buscar otros ejemplos en la web de cómo se llama ese elemento usualmente para proponer 1 o 2 textos:

+ "Enlace web"
+ "Enlace CSV"
+ "Enlace JSON"
+ *(...)*  (qué poner acá??)

**Comment by abenassi** [comment]
```

<script type="text/javascript" src="https://cdn.jsdelivr.net/gh/datosgobar/series-tiempo-ar-explorer@test_0.4/dist/js/main.js"></script>

<div id="root"></div>

<script>
    TSExplorer.render('root', {
        seriesApiUri: "https://apis-stg.datos.gob.ar/series/api",
        options: {}
    })
</script>

```

**Comment by abenassi** [comment]
1. Por qué el objeto se llama igual que el objeto de todo el explorador TSExplorer?? No debería ser un objeto más acotado que sea sólo el gráfico??
2. No hay parámetros (de la API), es la llamada entera a la API usando la URL para compartir JSON
3. Si yo paso un objeto a chartOptions vacío, anula otros elementos de configuración? Dicho de otra forma: lo mejor sería que cuando le paso un objeto sólo overrideo aquellas opciones que explícitamente pasé en el objeto, sin eliminar por omisión ninguna otra.
4. El usuario se puede llevar 2 tipos de gráficos embebibles:

a. Sin el navigator: muestra sólo los datos del período temporal elegido que están plasmados en la URL de la llamada a la API (`navigator=false`).
b. Con el navigator: muestra el gráfico siguiendo la misma lógica con la que se lo usa en el explorer. Se trae todos los datos de la API para habilitar un navigator sobre el rango completo de las series, pero tiene un rango temporal seleccionado para el zoom.

5. Incluir un link a la documentación como comentario en el JS.

**Comment by abenassi** [comment]
@alejandrosobko puede ser que te falte agregar el `navigator=false` todavía? La idea sería que venga por default en `navigator=true` (ahora que repensamos un poco como funciona) pero que igual el dev lo pueda "apagar" para sólo mostrar el gráfico sin poder cambiar el zoom y demás. Quedaría sólo el gráfico y la leyenda.

![Screenshot 2018-11-27 16.49.41.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5669d6f56378e7130054f97e/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cc6417763e7b53e37a26cbb771f1162a43434d0eee1e020a17b8eb8339a3e43f74dc5f5fe9806d0c27c43d11acb9d04ebd01be74825d99a4fedb1294b7607caddecd5d340c041f83fe5831a39a4fc05af343e74952b65e.png)

**Comment by alejandrosobko** [comment]
@abenassi la funcionalidad de navigator=false ya está, hace o no el request usando la fecha. Igualmente te dejo usar el navigator de highcharts porque es posible que tengas algun zoom para aplicar.

**Comment by abenassi** [comment]
ahh @alejandrosobko la idea es tener un parámetro con el cual no tener los zoom ni nada de eso, para usos en donde el gráfico es más chico y toda esa parte molesta

**Comment by abenassi** [comment]
Te agrego otra:

graphicUrl: 'https://apis.datos.gob.ar/series/api/series/?metadata=full&ids=168.1_T_CAMBIOR_D_0_0_26&limit=1000&start=0&start_date=2017-06-08',
            seriesApiUri: "https://apis.datos.gob.ar/series/api",

El parámetro `seriesApiUri` sobra, porque con la URL de la `graphicUrl` tenés todo lo necesario, no podemos sacarlo??
