### ISSUE TITLE
Agregar (izq) o (der) al texto de la leyenda

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-explorer#227]
Sólo cuando los dos ejes están siendo utilizados porque al menos una serie está asignada al eje auxiliar

**Comment by alejandrosobko** [comment]
Esto quiere decir que hay que diferenciar solamente en el caso en que una de las series esté fuera de escala?

**Comment by abenassi** [comment]
Si, o dicho de otra forma, si los dos ejes tienen al menos una serie activa.
