### ISSUE TITLE
Algunos elementos no se pueden clickear en mobile

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-explorer#233]
Como "Agregar series"

**Comment by alejandrosobko** [comment]
Tampoco se puede hacer zoom en el gráfico. @abenassi si podes fijate bien qué cosas no andan así ya corrijo todo.

**Comment by abenassi** [comment]
Ale, te dejo la tarea a vos de revisar que la experiencia completa que se
puede usar en el explorador, se pueda usar también en mobile. El testing
que podría hacer yo no va a ser muy diferente o mejor del que puedas hacer
vos.
