### ISSUE TITLE
Investigar si el slider puede incluir a todas las series

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-explorer#241]
Actualmente sólo muestra una de ellas

https://datosgobar.github.io/series-tiempo-ar-explorer/#/series/?ids=101.1_I2NG_2016_M_22,168.1_T_CAMBIOR_D_0_0_26&end_date=2015-12-01

**Comment by alejandrosobko** [comment]
Ese gráfico tiene un filtro de fechas, se ve una sola seria porque es la única serie en ese periodo.

**Comment by abenassi** [comment]
Pero me refería al slider de abajo que sirve para filtrar, ese debería
poder mostrar todas las series.
