### ISSUE TITLE
Revisar que no se haga query a destacados cuando no hace falta

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-explorer#252]
Sucede cuando se va a un link de un gráfico del explorer por primera vez.

**Comment by alejandrosobko** [comment]
@abenassi no es el mismo que #254?

**Comment by abenassi** [comment]
No no, son issues diferentes. El #252 es que en la vista de graficos se hacen las queries de la home innecesariamente. El #254 es que la home itera a traves del paginado para traerse *los datos* de toda la serie, cuando no es necesario. Fijate poniendo en dev de destacada una serie bien larga como los bonos de 10 años de estados unidos: tarda en cargar la home 6 es por que esta paginando varias queries a la API
