### ISSUE TITLE
Aplicar estilo para consultas con errores de "serie inexistente o vacía"

### ISSUE THREAD

**Issue by sebasbarraud** [datosgobar/series-tiempo-ar-explorer#256]
Los errores en la pantalla de las series no están estilizados. Usemos estos estilos para corregirlos:

Idealmente habría que agregar un ícono de Warning delante del texto como este: 
https://fontawesome.com/icons/exclamation-triangle?style=solid

Primer error: 

    margin: 20px -15px 20px -15px;
    padding: 20px;
    background-color: #ffdddd;
    border: 1px solid #ff9999;
    color: #ff5555;

Subsiguientes: 

    margin: 0px -15px 20px -15px;
    padding: 20px;
    background-color: #ffdddd;
    border: 1px solid #ff9999;
    color: #ff5555;

**Comment by sebasbarraud** [comment]
![Screen Shot 2018-11-08 at 18.27.17.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a2e9af60cb5b30011db881c/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226454fb6b7191a379e70c2956415e49be5d4a1f06a3a3dc78e2a436628f0e08e9876e0b70973d42ffba821fbf00e871894f81e2b59850d2aa6c7bb3d4d216744b470a83ed5c32aa984ecc59f14ae34855a71a3767f43b.png)

**Comment by sebasbarraud** [comment]
@abenassi

**Comment by abenassi** [comment]
@alejandrosobko cuando sólo se pasan series inexistentes (no hay series válidas) debería mostrarse la misma leyenda "roja" sin ningún gráfico.
