### ISSUE TITLE
Que el gráfico exportable no tenga un alto fijo

### ISSUE THREAD

**Issue by alejandrosobko** [datosgobar/series-tiempo-ar-explorer#279]
La idea es continuar teniendo el `height` actual en el gráfico del explorer, pero que en el componente exportable no esté seteado.

**Comment by abenassi** [comment]
[Uploading Screenshot 2018-12-26 12.02.49.png...]

**Comment by abenassi** [comment]
El gráfico del componente debería ocupar todo el espacio vertical y horizontal del contenedor que lo contenga.
