### ISSUE TITLE
Agregar parámetro al componente que permita elegir el metadato a mostrar en la leyenda

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-explorer#281]
Actualmente se muestra `description`, implementar un parámetro que contenga ese default pero permita cambiarlo por:

+ `title`
+ `id`

```
            header: "descriptions",
            header: "titles",
            header: "ids",
```

**Comment by abenassi** [comment]
@alejandrosobko idem al caso anterior, por favor aplicalo a algún caso en `componentes/index.html` para considerarlo en "Review", si no estaría en "Done" pero todavía no listo para que yo lo revise.

**Comment by abenassi** [comment]
@alejandrosobko `legendField: 'id'` funciona, pero `legendField: 'title'` no

**Comment by alejandrosobko** [comment]
@abenassi en realidad todos muestran `title`. Probá ponerle `description` y vas a ver que cambia.
