### ISSUE TITLE
Aumentar el tamaño vertical del gráfico en el explorer

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-explorer#284]
Aprovechando el espacio ganado eliminando los credits.

**Comment by abenassi** [comment]
![Screenshot 2019-01-03 13.11.36.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5669d6f56378e7130054f97e/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cd6416763e7957e37a23cbb279f1112d43434d0eee1e020a17b8eb8339a3e43f74dc5f5fe9806d0c27c43d11acb9d04ebd01be74825d99a4fedb1294b7607caddecd5d340c041f83fe5831a69c48c951f74ae04455b65e.png)

@alejandrosobko se puede reducir todo ese espacio que hay al final del gráfico antes de que esté el selector y demás opciones??

**Comment by alejandrosobko** [comment]
@abenassi hecho.
