### ISSUE TITLE
Traducir al español la fecha del mini-gráfico

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-explorer#287]

**Comment by abenassi** [comment]
![Screenshot 2019-01-06 23.15.43.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5669d6f56378e7130054f97e/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cd6416763e7952e37923cbb27df1162843434d0eee1e020a17b8eb8339a3e43f74dc5f5fe9806d0c27c43d11acb9d04ebd01be74825d99a4fedb1294b7607caddecd5d340c041f83fe5831a69149cf5cf249e44954b65e.png)

**Comment by alejandrosobko** [comment]
@abenassi  Lo estoy probando acá https://datosgobar.github.io/series-tiempo-ar-explorer y parece estar solucionado.

**Comment by alejandrosobko** [comment]
Efectivamente acá [3dd2f29](https://github.com/datosgobar/series-tiempo-ar-explorer/commit/3dd2f29a3c88fc6c9ef0f3bd1a4dd8e6ff7d53d0#diff-f24edef20801056033288aa5cff6047aR2) se agregó la internacionalización.
Cierro el issue, cualquier cosa lo reabrimos.
