### ISSUE TITLE
Implementar selector de unidades (representation_mode) global

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-explorer#288]

**Comment by abenassi** [comment]
@abenassi revisar los textos del selector

**Comment by alejandrosobko** [comment]
Es un dropdown como el selector de frecuencia? Qué hacemos cuando el usuario lo pasa por URL?

**Comment by abenassi** [comment]
Sí, debería ser un dropdown como el selector de frecuencia. Si el usuario
lo pasa por URL, el dropdown debería mostrarlo seleccionado.
