### ISSUE TITLE
Implementar selector de tipo de gráfico global

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-explorer#291]
Hay que agregar un parámetro a la URL chartType o chart_type (según sea la convención REST para parámetros) que recoja esto cuando es "column" en lugar de "line" para que el link web siga manteniendo las características elegidas por el usuario cuando lo comparte.

Esto sólo afecta al link web (el que se ve en la URL del navegador y el que se comparte con "Enlace web"), no a los links que son llamadas a la API. También afecta al componente web portable.

+ default
+ line
+ column
+ area

**Comment by alejandrosobko** [comment]
Esto afecta al gráfico que vemos en el explorer? Si a la url le agrego `&charType=bar` el gráfico en el explorer pasa a ser de barras en lugar del actual?

**Comment by abenassi** [comment]
Exactamente. Si te parece en el mismo issue, estaría bueno implementarlo de
forma tal que sean posibles tanto:

&chartType=bar

&chartTypes=11.3_VMATC_2004_M_12:bar,143.3_NO_PR_2004_A_21:area

te parece?? O issues separados?? Incorporar a la UI el selector de tipo de
gráfico *global* sólo requiere el primero en realidad, pero sumaría agregar
lo otro también para que ya se empiece a poder usar al menos a nivel de URL.

**Comment by alejandrosobko** [comment]
Agregaría como primer issue la función de elegir qué tipo de gráfico queremos, con selector, url y todo. Y en otro como mejora, elegirlo para cada serie.
