### ISSUE TITLE
Implementar versiones "largas" del formato de fechas

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-explorer#293]
Anual: 2018

Semestral: 1º semestre 2018 /  2º semestre 2018

Trimestral: 1º trimestre 2018 /  2º trimestre 2018 / 3º trimestre 2018 /  4º trimestre 2018

Mensual: Septiembre 2018

Diaria: 23 Septiembre 2018

**Comment by alejandrosobko** [comment]
Recuperé el tooltip de fecha, actualizado en `index.html` e `index2.html` de la carpeta `/componentes`. Recordemos que el tooltip tiene un issue en pantallas relativamente chicas cuando agregamos varios gráficos en la misma línea. Pero dicho issue ya tiene una tarea creada.
