### ISSUE TITLE
Fijar tamaños de algunas zonas del componente para que siempre quede el gráfico del mismo tamaño

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-explorer#296]
Desde arriba a abajo y por cada uno de los 3 casos de componentes:

**Gráfico completo**

(ie. es más ancho que 700px)

+ El título tiene 1 línea o más (comportamiento actual)
+ Cuando el zoom y el filtro de fechas están a izquierda y derecha *tal como están ahora*.

**Gráfico chico**

(ie. es igual o más chico que 700px)

+ El título tiene 2 líneas (por lo menos) o más (podríamos llegar a querer aumentar este mínimo de líneas a 3 cuando lo probemos)
+ Cuando el zoom y el filtro de fechas no entran en la misma línea, quedan centrados (en lugar de uno a la derecha y otro a la izquierda).
+ El gráfico se expande hasta ocupar el espacio disponible
+ El footer que tiene la leyenda + la fuente tiene un alto fijo de 7 líneas (5 de leyenda + 2 de fuente, que termina con ellipsis si excede las 2 líneas).

**Comment by alejandrosobko** [comment]
Quedó el título con 2 líneas y scroll. El zoom fue alineado a la derecha porque alinearlo al centro no funciona bien (imagino que por los ajustes manuales que le hacemos). 
Sobre el footer, no tenemos forma de modificar la leyenda, esa feature fue deprecada. Sólo pude hacer que el subtítulo no se pise con los créditos.
