### ISSUE TITLE
Agregar "título" default

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-explorer#299]
Si el gráfico es monoserie: se pone como título el "field_description" de la serie.

Si el gráfico es multiserie: se pone como título el "dataset_title" de la primer serie.

El componente en sí solamente implementa una variable para cambiar el título del gráfico. El default se aplica desde el explorer, en el código que se copia al compartir el gráfico embebible, de tal forma que se sugiere al usuario un default que puede cambiar.

Parámetro: `title`

**Comment by alejandrosobko** [comment]
@abenassi Si el usuario que utiliza el código compartido *borra* la variable `legendField` usaríamos el default del componetne exportable, no? Es decir  "description".
La lógica para ver cuál recomendar es justamente eso no? Recomendar un campo pero si se borra no se usa, estamos ok?
