### ISSUE TITLE
Implementar 10 colores de argentina.gob.ar

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-explorer#302]
Son los que están en los ejemplos demo 

["#0072BB", "#2E7D33", "#C62828", "#F9A822", "#6A1B99", "#EC407A","#C2185B","#6A1B99","#039BE5","#6EA100"]

Deberían estar en el componente seteados por default, pero deberían poder overridearse si el usuario así lo quiere.

**Comment by alejandrosobko** [comment]
@abenassi el color "6A1B99" está repetido. Lo dejo solo una vez y quedan 9 o me pasas otro en su lugar?

**Comment by abenassi** [comment]
Mmm por ahora dejalo con 9

**Comment by abenassi** [comment]
Cambiar el orden para que siga este: ["#0072BB", "#2E7D33", "#C62828", "#F9A822", "#6A1B99", "#EC407A","#C2185B","#6A1B99","#039BE5","#6EA100"]
