### ISSUE TITLE
Revisar comportamiento y tamaño vertical en distintos escenarios

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-explorer#309]
```
<script type='text/javascript' src='https://cdn.jsdelivr.net/gh/datosgobar/series-tiempo-ar-explorer@ts_components_1.9.0/dist/js/components.js'></script>
<script type='text/css' src='https://cdn.jsdelivr.net/gh/datosgobar/series-tiempo-ar-explorer@ts_components_1.9.0/dist/css/components.css'></script>
<div id="root"></div>
<script>
    window.onload = function() {
        TSComponents.Graphic.render('root', {
            graphicUrl: 'https://apis-stg.datos.gob.ar/series/api/series/?metadata=full&end_date=2017-08-01&ids=103.1_I2N_2016_M_15,173.1_INUCLEOLEO_DIC-_0_10&limit=1000&start=0&start_date=2016-06-01',
            chartOptions: { // Override highstock configs. See https://api.highcharts.com/highstock/
            },
            navigator: false,
            locale: 'AR',
            zoom: true,
            datePickerEnabled: true,
            exportable: true,
            colors: ['#0072BB','#039BE5','#2E7D33','#6EA100','#F9A822','#EC407A','#C2185B','#C62828','#6A1B99'],
            backgroundColor: '#ffffff00',
            title: 'dataset_title',
            source: 'Instituto Nacional de Estadística y Censos (INDEC)',
        })
    }
</script>
```

**Comment by abenassi** [comment]
![Screenshot 2019-02-13 09.58.18.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5669d6f56378e7130054f97e/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cd6416753e7857e37b29cbb670f1132343434d0eee1e020a17b8eb8339a3e43f74dc5f5fe9806d0c27c43d11acb9d04ebd01be74825d99a4fedb1294b7607caddecd5d340c041083fe5830a0994dca5ff74de84c51b65e.png)

**Comment by abenassi** [comment]
Se corta cuando el espacio horizontal es acotado y necesita más líneas

![Screenshot 2019-02-13 10.03.41.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5669d6f56378e7130054f97e/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cd6416753e7857e37a20cbb37bf1162a43434d0eee1e020a17b8eb8339a3e43f74dc5f5fe9806d0c27c43d11acb9d04ebd01be74825d99a4fedb1294b7607caddecd5d340c041083fe5830a0994dcb58f44fe24953b65e.png)

**Comment by abenassi** [comment]
Chequear que el criterio adoptado quede bien con los créditos

**Comment by abenassi** [comment]
```
<script type='text/javascript' src='https://cdn.jsdelivr.net/gh/datosgobar/series-tiempo-ar-explorer@ts_components_1.11.3/dist/js/components.js'></script>
<script type='text/css' src='https://cdn.jsdelivr.net/gh/datosgobar/series-tiempo-ar-explorer@ts_components_1.11.3/dist/css/components.css'></script>
<div id="root"></div>
<script>
    window.onload = function() {
        TSComponents.Graphic.render('root', {
            graphicUrl: 'https://apis-stg.datos.gob.ar/series/api/series/?metadata=full&end_date=2017-08-01&ids=103.1_I2N_2016_M_15,173.1_INUCLEOLEO_DIC-_0_10&limit=1000&start=0&start_date=2016-06-01',
            chartOptions: { // Override highstock configs. See https://api.highcharts.com/highstock/
            },
            source: 'Instituto Nacional de Estadística y Censos (INDEC), Banco Central de la República Argentina (BCRA)',
        })
    }
</script>
```

@alejandrosobko te paso 4 temas que cuando revisamos con vos en dev ya estaban resueltos y ahora parece como si los cambios hubieran vuelto para atrás.

+ Exportable (debe ser False por default) 
+ Centrado de zoom y datePickerEnabled (cuando dejan de estar en la misma línea, deben estar centrados en lugar de izquierda y derecha, el proxy para implementar esto es poner un límite en px al ancho del gráfico a partir del cual se centran)
+ La y de INDEC (habíamos visto que el footer tenía dos líneas wrapeadas y funcionaba bien, ahora volvió para atrás).
+ El gráfico parece rígido en su tamaño vertical (esto lo comento en otro issue, pero me parece que es la fuente de los problemas en general).

**Comment by alejandrosobko** [comment]
- exportable: hecho
- centrado de zoom y datepicker: cargado en otro issue
- la `y`: debe ser un problema con los estilos. No lo puedo reproducir
- gráfico rígido: lo mismo que el anterior. El gráfico toma el alto del contenedor. Hay que revisar los estilos en el caso de uso, lo probé con el código reportado y no sucede. En slack dejé un ejemplo.
