### ISSUE TITLE
Reducir el espacio entre el gráfico y la leyenda

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-explorer#324]
Cuando el gráfico es verticalmente chico, no tiene navigator y tiene leyenda, el espacio entre el gráfico y la leyenda es demasiado grande y hace que se achique demasiado el gráfico.

Investigar si es un estilo que actúa cuando el gráfico es menor a X px verticalmente y si actúa sólo cuando navigator = False.

**Comment by alejandrosobko** [comment]
Hay algun ejemplo de esto? Te dejo la captura de un gráfico de 600x380 donde lo veo funcionar bien.

![Pasted_image_at_2019-03-07__3_13_PM](https://user-images.githubusercontent.com/11604761/54277918-d17fa280-456f-11e9-8d03-37a57a085cc0.png)

**Comment by abenassi** [comment]
Fijate en alguno de los ejemplos en el repo de demo que estan en la carpeta
de argentinagobar (especialmente el hacienda-embed.html) posiblementese vea
mal a partir de cierto tamaño mas chico en adelante. (Estoy en la calle y
no te puedo mandar screenshot)
