### ISSUE TITLE
Implementar una variable que permita cambiar las etiquetas de la leyenda

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-explorer#331]
`legendLabel`: object 

sería un objeto {<id de serie>: <etiqueta alternativa>} que permite especificar etiquetas a usar alternativas para una, varias o todas las series del gráfico en lugar de tomar el texto del `legendField` correspondiente.

**Comment by abenassi** [comment]
@alejandrosobko te lo vuelvo para atrás porque el campo no está documentado. Voy a estar testeando que estas cosas se puedan usar en forma efectiva desde la documentación como usuario, si no no lo consideramos como "Done".

**Comment by alejandrosobko** [comment]
Agregada la documentación del campo `legendLabel` .
