### ISSUE TITLE
Implementar "ver más" en los filtros

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-explorer#343]

**Comment by alejandrosobko** [comment]
Qué se supone que hace? Dónde va?

**Comment by abenassi** [comment]
La idea es que los filtros de la búsqueda sólo muestren las primeras 5
categorías, y si se clickea en "Ver más" muestren el resto. Hoy es difícil
navegar los filtros porque hay algunos que tienen muchas categorías.

**Comment by abenassi** [comment]
https://stg.datos.gob.ar/series/api/search/?q=

Falta "salud" en los filtros de "Catálogos" cuando se hace click en "Ver más", y la API sí lo devuelve.

<img width="319" alt="Screenshot 2019-05-23 18 23 55" src="https://user-images.githubusercontent.com/4405346/58287723-2158c200-7d88-11e9-9869-380dd6044cbc.png">
<img width="1344" alt="Screenshot 2019-05-23 18 23 36" src="https://user-images.githubusercontent.com/4405346/58287724-2158c200-7d88-11e9-906d-15b2d53fd1d6.png">
