### ISSUE TITLE
En mobile no se pueden agregar series a una serie ya seleccionada (no aparecen en la búsqueda)

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-explorer#347]
Probado con un Android / Chrome.

No parece pasar lo mismo haciendo la prueba en una computadora con el inspector de Chrome haciéndose pasar por un celular.

**Comment by alejandrosobko** [comment]
Estuve haciendo pruebas pero no logro reproducirlo. Tenes alguna url de ejemplo?

**Comment by abenassi** [comment]
No, porque pasa cuando lo hago desde un celular... Tenés que abrir
cualquier serie en un celular Android / Chrome y después tratar de agregar
una nueva serie buscando en el "Agregar series".

**Comment by lucaslavandeira** [comment]
No reproducible
