### ISSUE TITLE
El explorador toma como "no existentes" series que están correctamente indexadas en la API

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-explorer#357]
https://datos.gob.ar/series/api/series/?ids=AGRO_0201 se toma como con existente pero https://apis.datos.gob.ar/series/api/series/?ids=AGRO_0201 devuelve datos y metadatos correctamente.

Esto parece estar pasando sólo con las series de Agro, y con casi todas ellas.

+ Revisar qué falla de la lógica del explorer en entender la situación
+ Revisar qué puede robustecerse del lado de la API también, en términos de su respuesta

**Comment by lucaslavandeira** [comment]
Solucionado en #358
