### ISSUE TITLE
Las escalas no funcionan bien

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-explorer#366]
https://stg.datos.gob.ar/series/api/series/?ids=148.3_INIVELNAL_DICI_M_26,99.3_IR_2008_0_9,99.1_IR_2008_0_9,96.3_IBV_2008_M_13

<img width="1283" alt="Screenshot 2019-05-24 15 18 43" src="https://user-images.githubusercontent.com/4405346/58348486-40625d00-7e37-11e9-9a63-032caab42951.png">

El eje señalado debería estar a la derecha, y además debería estar formateado como porcentaje porque la API de series devuelve "is_percentage: true".

https://apis.datos.gob.ar/series/api/series/?ids=148.3_INIVELNAL_DICI_M_26,99.3_IR_2008_0_9,99.1_IR_2008_0_9,96.3_IBV_2008_M_13&metadata=full  (ver metadato de la última serie al final de todo)

<img width="633" alt="Screenshot 2019-05-24 15 22 06" src="https://user-images.githubusercontent.com/4405346/58348696-bb2b7800-7e37-11e9-96d6-9b898fe21003.png">

**Comment by alejandrosobko** [comment]
@abenassi en el frontend pusimos la lógica para saber si la serie tiene que ser formateada a porcentaje, y especificamos que si los valores estaban entre 0 y 1 era formateada, sino no. Esa serie tiene un valor que es 1.05, por lo cual no fue formateada. Si te parece, borro la lógica y uso el valor de la API `is_percentage`.

**Comment by abenassi** [comment]
Ahh ok, cierto! Esa lógica era necesaria cuando no existía el valor
"is_percentage".

Si te parece (para que sea más robusto el explorer) lo mejor sería hacer un
chequeo de si el atributo "is_percentage" está explicitado:

+ si lo está, tomás true / false de ahí
+ *si no lo está*, inferís true / false a partir de la lógica ya
implementada.
