### ISSUE TITLE
Revisar elementos que rompen en el contexto de argentina.gob.ar

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-explorer#403]
Usar https://datosgobar.github.io/series-tiempo-ar-explorer-demo/dashboard/argentina/hacienda/ como prueba para ver que las cards funcionan bien en el contexto de argentina.gob.ar.

+ Rompe el mini gráfico
+ Rompen los enlaces
+ El color de la barra no cambia

Veo que no se puede importar la librería de bootstrap porque choca con los estilos de poncho y no podemos hacer eso. Habría que ver si usamos algo de esa versión de boostrap que no esté en Poncho (http://argob.github.io/poncho/) *que sea crítico* o si hay algo mejor para reemplazarlo. A primera vista no parece ser muy problemático, rompe por otro lado.

**Comment by lucaslavandeira** [comment]
- Versión de Font-Awesome compatible, que posea el icono de "salir de página" (usado en el Ver Más por Poncho)
- Dropdown de enlances no anda
