### ISSUE TITLE
Testear el uso del componente en navegadores viejos

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-explorer#404]
- Internet Explorer Versión 9 y superior
- Chrome Versión 32 y superior
- Firefox Versión 27 y superior
- Safari Versión 7 y superior

**Comment by lucaslavandeira** [comment]
- Bien con Firefox 29 y arriba

- Bien con IE11, `axios` no tiene soporte para ie9 y 10, y tenemos una fuerte dependencia con ellos.

- Chrome no ofrece versiones viejas por razones de seguridad, se comprueba que funciona bien con Chrome 73
