### ISSUE TITLE
Revisar por qué los estilos se ven ligeramente rotos (posición y padding alrededor de algunos textos) en mkdocs

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-explorer#427]
https://datosgobar.github.io/series-tiempo-ar-explorer/reference/ts-components/card/

Tal vez hay algo que se pueda robustecer del CSS de las tarjetas, o tal vez hay que aplicarlo a esta web específica.

**Comment by pepeciavirella** [comment]
Cerrado con el PR #425
