### ISSUE TITLE
Revisar estilos que se pisan entre el gráfico y la leyenda

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-explorer#442]
![Screenshot 2019-07-31 10 41 20](https://user-images.githubusercontent.com/4405346/62216820-dce93400-b37f-11e9-8d91-703f0c44b1e9.png)

**Comment by pepeciavirella** [comment]
Esto puede solucionarse por fuera del componente, setenadole al `div` que contiene el componente rendereado una propiedad de altura de CSS, con algo como `style="height: 700px;`, o los pixeles que sean necesarios. Esta inyección de altura por fuera del componente podría contribuir al concepto del issue #449
