### ISSUE TITLE
Revisar que el gráfico de area debería ser area

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-explorer#445]
![Screenshot 2019-07-31 11 00 32](https://user-images.githubusercontent.com/4405346/62218269-7e718500-b382-11e9-85c1-8cbd736cc3c3.png)

**Comment by pepeciavirella** [comment]
Motivación del issue movida al issue #453, siendo este último la causa del mal comportamiento descrito acá.
