### ISSUE TITLE
Revisar manejo de la escala (hay una serie por lo menos que debería estar en un eje distinto que las otras)

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-explorer#447]
![Screenshot 2019-07-31 11 10 26](https://user-images.githubusercontent.com/4405346/62219001-e70d3180-b383-11e9-8ad4-9bb52111a26a.png)

**Comment by lucaslavandeira** [comment]
Era un bug del backend, corregido en datosgobar/series-tiempo-ar-api#589
