### ISSUE TITLE
Spike: cómo se setearía el tamaño vertical de un chart cuando se quiere dejar fijo

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-explorer#449]
![Screenshot 2019-07-31 11 34 22](https://user-images.githubusercontent.com/4405346/62220878-28eba700-b387-11e9-8afc-a9f7a6892c14.png)
![Screenshot 2019-07-31 11 33 38](https://user-images.githubusercontent.com/4405346/62220890-2b4e0100-b387-11e9-9940-d000aacdd891.png)

**Comment by pepeciavirella** [comment]
Actualmente, se está seteando la altura del `chart` del `Graphich` luego de que este se renderee, haciendo una suerte de corrección/ajuste. La misma consiste en que la altura del `chart` (el gráfico en sí, es decir la suma de ejes, ordenadas, abscisas y dibujo de las series) debe ser la diferencia entre la altura del contenedor (`container`) y la altura de la fuente escrita debajo (el `subtitle`)-

Si bien esto es lógico, podría agregarse un parámetro opcional al componente `Graphic` que, en caso de estar especificado, permita forzar que la altura del `chart` sea el valor de dicho parámetro. En caso de omitirse éste, podría realizarse el ajuste correspondiente.

**Comment by lucaslavandeira** [comment]
Además, haciendo un cambio menor en el código, podemos permitir que se utilice `chartOptions` para hacer este manejo de altura. Highcharts provee un parámetro `chart: { height: xxx }` para manejar la altura del gráfico (sólo el gráfico, sin navigator, sin leyenda). 

Las dos propuestas terminan siendo
- Parámetro adicional del componente
- Usar `chartOptions` (posible luego de un fix en el código)

Ambas opciones son igual de simples de implementar.
