### ISSUE TITLE
Validar URLs pasadas a componente Graphic

### ISSUE THREAD

**Issue by pepeciavirella** [datosgobar/series-tiempo-ar-explorer#461]
Mejorar la validación actual del parámetro `graphicUrl` que se le pasa a los componentes `Graphic`. Debería validarse que los query params pasados sean sólo los posibles, y que haya valores lógicos para los mismos. A su vez, deberían lanzarse excepciones _user-friendly_, que sean entendibles por los usuarios.

**Comment by abenassi** [comment]
No debe validarse el dominio / IP / instancia de la API (el componente debe poder pegarle a cualquier instancia del proyecto series-tiempo-ar-api que exista en cualquier URI), debe validar desde /series? en adelante.

En esta URL:
https://apis-stg.datos.gob.ar/series/api/series/?ids=148.3_INIVELNAL_DICI_M_26&collapse_aggregation=sum

NO se valida
https://apis-stg.datos.gob.ar/series/

SI se valida
/api/series/?ids=148.3_INIVELNAL_DICI_M_26&collapse_aggregation=sum
