### ISSUE TITLE
Graphic comete errores al generar la llamada interna a la API

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-explorer#467]
Esto provoca que se rompa el gráfico. Se comprobó al agregar un &start_date=2001 al graphicUrl.

Graphic convierte la llamada 

https://apis.datos.gob.ar/series/api/series?ids=116.4_TCRZE_2015_D_36_4,75.3_IETG_0_M_31&start_date=2001 

en 

https://apis.datos.gob.ar/series/api/series/?ids=116.4_TCRZE_2015_D_36_4,75.3_IETG_0_M_31&start_date=2001/series/&metadata=full&ids=116.4_TCRZE_2015_D_36_4,75.3_IETG_0_M_31&limit=5000&start=0

```
TSComponents.Graphic.render('itcrm-exportaciones', {
                graphicUrl: "https://apis.datos.gob.ar/series/api/series?ids=116.4_TCRZE_2015_D_36_4,75.3_IETG_0_M_31&start_date=2001",
                chartTypes: {
                    "75.3_IETG_0_M_31": "column"
                },
                seriesAxis: {
                    "75.3_IETG_0_M_31": "right"
                },
                datePickerEnabled: true,
                displayUnits: true,
                // title: "IPC",
                zoom: true,
                navigator: true,
                legendLabel: {
                    "116.4_TCRZE_2015_D_36_4": "ITCRM",
                    "75.3_IETG_0_M_31": "Exportaciones FOB"
                }
            })
```

**Comment by AWolfsdorf** [comment]
@abenassi,

El problema está en que la url que le estas pasando esta mal escrita, le falta un slash despues de "/series", tendria que ser "/series/?ids=...." en vez de "/series?ids=...." 

Pasando de:

https://apis.datos.gob.ar/series/api/series?ids=116.4_TCRZE_2015_D_36_4,75.3_IETG_0_M_31&start_date=2001

a

https://apis.datos.gob.ar/series/api/series/?ids=116.4_TCRZE_2015_D_36_4,75.3_IETG_0_M_31&start_date=2001

Debería funcionar.

**Comment by AWolfsdorf** [comment]
Se reabre el issue ya que el explorer deberia tomar esa api call como válida
