### ISSUE TITLE
Agregar parámetro "collapse" a la tarjeta

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-explorer#468]
El parámetro `collapse` debe agregarse a la llamada a la API para permitir al usuario de `Card` que modifique la agregación temporal de la serie que está pidiendo.

**Comment by mfigueroa1** [comment]
Agregar o modificar, la frecuencia Semanal (Week) de una serie.

![Image 1 1](https://user-images.githubusercontent.com/53904199/63543450-4250c080-c4f9-11e9-83f2-9ed7ee11cdf5.png)


![Image 1 2](https://user-images.githubusercontent.com/53904199/63543452-4250c080-c4f9-11e9-83c5-26baf63d3704.png)
