### ISSUE TITLE
El selector de fechas del explorer no funciona bien

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-explorer#473]
![explorer-date-error](https://user-images.githubusercontent.com/4405346/62975929-e51a8800-bdf1-11e9-83aa-00b8a376eda6.gif)

**Comment by pepeciavirella** [comment]
**UPDATE**:

Lo ejemplificado en el GIF del 13/08/2019 ya no ocurre más actualmente. Sin embargo, ahora se desean corregir dos comportamientos más:
- El formato de la fecha elegible en el input para el selector de fechas debería ser sensible a la frecuencia de abscisas del gráfico renderizado. Es decir, si las abscisas son años, el input debería admitir sólo fechas de tipo `AAAA`.
- El input no debería separarse del placeholder del selector en sí, sino que debería poder editarse in situ, desde el mismo placeholder.
