### ISSUE TITLE
Revisar estilos de la tarjeta: la fuente queda con muy poco margen al final

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-explorer#494]
<img width="261" alt="Screenshot 2019-09-03 08 24 39" src="https://user-images.githubusercontent.com/4405346/64169617-90809080-ce24-11e9-910f-caa7731d852a.png">

**Comment by pepeciavirella** [comment]
Comportamiento erróneo en explorer-demo/poncho/plantillas/dashboard.html
Comportamiento correcto en explorer-demo/card/index.html
