### ISSUE TITLE
El gráfico debería ser todo de column

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-explorer#501]
Cuando se usa `chartType` en el Explorer.

https://datosgobar.github.io/series-tiempo-ar-explorer/#/series/?ids=apis_georef_002,apis_georef_002:change&collapse=month&collapse_aggregation=avg&chartType=column

**Comment by mfigueroa1** [comment]
Adjunto gif del Test

![test2](https://user-images.githubusercontent.com/53904199/65969350-02a3bf80-e43b-11e9-97ca-8871d31d7e13.gif)
