### ISSUE TITLE
Agregar separador de miles al formato de números en el explorer y en los componentes

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-explorer#513]

**Comment by mfigueroa1** [comment]
Se verifica que el ticket ha sido resuelto correctamente

![QA](https://user-images.githubusercontent.com/53904199/67237324-69583f80-f421-11e9-826d-eb4c649ea201.gif)


![QA1](https://user-images.githubusercontent.com/53904199/67237503-c5bb5f00-f421-11e9-8492-1669f575ee6f.gif)
