### ISSUE TITLE
El parámetro `chartType` tiene un comportamiento extraño con la escala de las series

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-explorer#524]
https://datos.gob.ar/series/api/series/?ids=ddaa_apn_005

tiene la escala esperada

https://datos.gob.ar/series/api/series/?ids=ddaa_apn_005&chartType=column

cambiar el tipo de gráfico a "columna" incrementa la escala inexplicablemente

**Comment by AWolfsdorf** [comment]
Esto sucede ya que la el valor por defecto en las configuraciones de HighCharts para series de tipo Columna es de ["sum"](https://api.highcharts.com/highstock/plotOptions.column.dataGrouping) es decir que se hace una agregación de suma para casos donde la cantidad de datos a mostrar sea muy grande. Se puede ver en la serie del issue que si se le hace zoom la escala se corrije.
Esto se puede arreglar agregando esta linea de codigo a la configuracion en helpers/chartConfigBuilder.ts donde se crea la configuración general del chart.
`plotOptions : { series: { dataGrouping: { approximation: "average" } } }`.
El problema de esto es que talvez no es lo buscado para ciertas series, en cualquier serie de datos parciales esto causaria que te muestre el promedio en vez de la suma, lo cual seria lo esperado en estos casos.

**Comment by pepeciavirella** [comment]
@AWolfsdorf probaste con alguno de estos parámetros https://api.highcharts.com/highstock/plotOptions.column.dataGrouping ?? Al parecer, se puede aplicar eso mismo que decís a `column`, no a todo `series`, e incluso especificar si habilitar el agregado o no (con `enabled`, lo cual suena tal vez a menos influyente que definir agregado de promedio para tooodas las series), o bien setear un `groupPixelWidth` muy chico (cosa que permita tener puntos muy juntos, como en el caso de las series con muchos valores de abscisas)

**Comment by AWolfsdorf** [comment]
@pepeciavirella Si, el tema es que esto del agregado, como menciono en mi comment, no es lo correcto para todos los tipos de series, en caso de series parciales (montos de ingresos diarios/mensuales/etc) no es lo correcto hacer un agregado promedio (Ej: serie diaria, ingresó 1000 por dia, se agrega semanalmente, promedio 1000 cuando en verdad entró 7000 en toda la semana)
