### ISSUE TITLE
El orden de las series en la leyenda y para la asignación de colores, no respeta el orden de los ids en la llamada a la API

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-explorer#525]
https://datosgobar.github.io/series-tiempo-ar-explorer-demo/demos/defensa

Las llamadas y los objetos están armadas para que respeten el mismo orden de la API y tengan los mismos colores, pero el componente graphic parece ordenar por orden alfabético.

**Comment by mfigueroa1** [comment]
Se probó cambiando el Id de la serie al final del parámetro, se visualiza como el gráfico cambia de azul a rojo respetando el orden de los Id 


![qa23](https://user-images.githubusercontent.com/53904199/66423890-f42d4900-e9e2-11e9-9e5c-8c9a68f815d3.gif)
