### ISSUE TITLE
Implementar parámetros start_date y end_date que permitan aplicar el zoom inicial desde el objeto JS

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-explorer#559]
**Contexto**

Se desea poder inicializar un `graphic` con un zoom ya aplicado seteando start_date, end_date o ambos, sin hacerlo desde la llamada a la API para preservar la posibilidad del usuario de modificarlo.

**Propuesta**

Implementar los 2 nuevos parámetros para setear un zoom inicial distinto del 100% actual, a partir de fechas.

<img width="1135" alt="Screenshot 2019-10-28 16 59 48" src="https://user-images.githubusercontent.com/4405346/67713577-d41af500-f9a4-11e9-994a-eb990e549ed9.png">

**Comment by AWolfsdorf** [comment]
Se encontró un problema el cual, cuando no se especificaba el navigator, el componente enviaba en la query los parametros pasados.
Para corregir la implementación del mismo lo dejamos en block hasta el miercoles.
