### ISSUE TITLE
No se pueden borrar series del gráfico

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-explorer#578]
https://datos.gob.ar/series/api/series/?ids=143.3_NO_PR_2004_A_21,143.3_NO_PR_2004_A_21:percent_change_since_beginning_of_year&start_date=2016-01-01

<img width="1431" alt="Screenshot 2019-11-18 13 12 56" src="https://user-images.githubusercontent.com/4405346/69069460-42336480-0a05-11ea-86f2-f2523e29b09d.png">

**Comment by LorenaMelgarejo** [comment]
Las series del gráfico pueden ser eliminadas si el dropdown de **"Unidades"** se encuentra en la opción **"Unidades Originales"**, en cambio si se encuentra en las otras opciones (Ej: **Variación porcentual**), no efectúa la acción de elimina .

![gifEliminar](https://user-images.githubusercontent.com/22152649/69262796-da1a8500-0ba2-11ea-8427-517515c8ed34.gif)
